// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFzVqGMJizcnHDH0ZefYVn51KtQgHT2Dw',
    appId: '1:578327012717:web:9c712c1de5e77b7854a664',
    messagingSenderId: '578327012717',
    projectId: 'fleet-1b595',
    authDomain: 'fleet-1b595.firebaseapp.com',
    storageBucket: 'fleet-1b595.firebasestorage.app',
    measurementId: 'G-PC06ZCEQ9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEEJbczP-zsBco18NCr_wBsLjrT-Q1uPI',
    appId: '1:578327012717:android:ee66adc32d291f7154a664',
    messagingSenderId: '578327012717',
    projectId: 'fleet-1b595',
    storageBucket: 'fleet-1b595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXDxBHdENAJtVHx80znkM8hmHPM7gcpxk',
    appId: '1:578327012717:ios:f01301f2a145e8cf54a664',
    messagingSenderId: '578327012717',
    projectId: 'fleet-1b595',
    storageBucket: 'fleet-1b595.firebasestorage.app',
    iosBundleId: 'com.example.fleetManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXDxBHdENAJtVHx80znkM8hmHPM7gcpxk',
    appId: '1:578327012717:ios:f01301f2a145e8cf54a664',
    messagingSenderId: '578327012717',
    projectId: 'fleet-1b595',
    storageBucket: 'fleet-1b595.firebasestorage.app',
    iosBundleId: 'com.example.fleetManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFzVqGMJizcnHDH0ZefYVn51KtQgHT2Dw',
    appId: '1:578327012717:web:f6572c8cfe3b9d3254a664',
    messagingSenderId: '578327012717',
    projectId: 'fleet-1b595',
    authDomain: 'fleet-1b595.firebaseapp.com',
    storageBucket: 'fleet-1b595.firebasestorage.app',
    measurementId: 'G-1PY3G239FC',
  );
}
